apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test-component"
  description: "this is a example"
  annotations:
    github.com/project-slug: diegosantillan-coder/repository-week
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: "group:default/guests"